name             'zip_build'
maintainer       'Justin Alan Ryan (ZipRealty / Realogy)'
maintainer_email 'juryan@ziprealty.com'
license          'Apache 2.0'
description      'Installs/Configures zip_build'
long_description 'Installs/Configures zip_build'
version          '0.2.1'

depends 'java'
depends 'maven'
depends 'poise-python'
depends 'rbenv'
depends 'git'
depends 'nodejs'
depends 'chef-dk'
depends 'zip_common'
depends 'debian'

