node.default['java']['jdk_version'] = '8'
default[:zip_build][:deployment_scripts_path] = '/opt/deployment_scripts'
default[:zip_build][:deployment_scripts_url] = 'http://juryan@stash.aur.ziprealty.com:7990/scm/ops/deployment_scripts.git'
default[:zip_build][:bamboo_agent_version] = '5.12.3.1'
default[:zip_build][:bamboo_agent_home] = '/srv/bamboo'
default[:zip_build][:bamboo_user_home] = '/home/zip'
